ITU-BDSA2024-GROUP4/Chirp

.github/workflows/publish.yml

Co-authored-by: ChatGPT <>
Co-authored-by: Bergur <berd@itu.dk>
Co-authored-by: Victor <visf@itu.dk>

Fix github action publish

---

.github/workflows/publish.yml
src/Chirp.CLI/Chrip.CLI.csproj

Co-authored-by: Bergur <berd@itu.dk>
Co-authored-by: Victor <visf@itu.dk>

Push last changes

---

.github/workflows/publish.yml

Co-authored-by: Bergur <berd@itu.dk>
Co-authored-by: Victor <visf@itu.dk>

Fix publish action path

---

src/SimpleDB/CSVDatabase.cs

co-authored-by: Bergur <berd@itu.dk>
co-authored-by: Mikkel <mikcla@itu.dk>
co-authored-by: Lucas <lucasveha@gmail.com>

CSV database moved to correct location in FS

---

.github/workflows/build_and_test.yml
.github/workflows/publish.yml
src/Chirp.CLI/Chirp.CLI.csproj
src/Chirp.CLI/Program.cs
src/Chirp.CSVDBService/Chirp.CSVDBService.csproj
src/SimpleDB/SimpleDB.csproj
test/Chirp.CLI.Tests/Chirp.CLI.Tests.csproj
test/Chirp.CLI.Tests/UnitTest1.cs
test/Chirp.SimpleDB.Tests/Chirp.SimpleDB.Tests.csproj

Migrated from .NET 7 to .NET 8

Migrate to .NET 8 Co-authored-by: Allan <Allp@itu.dk> Co-authored-by: Lucas <lucasveha@gmail.com> Co-authored-by: Mikkel <mikcl@itu.dk>

---

src/Chirp.CSVDBService/Chirp.CSVDBService.csproj

- **Fix names Chrip to Chirp Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Fix names Chrip to Chirp Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Fix no dll created Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Victor <visf@itu.dk> Co-authored-by: Allan <allp@itu.dk>**

fix not creating dll

---

src/SimpleDB/CSVDatabase.cs
src/SimpleDB/SimpleDB.csproj

- **Fix names Chrip to Chirp Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Fix names Chrip to Chirp Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Fix no dll created Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Victor <visf@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Add chirp_cli_db.csv to publish directory Co-authored-by: Mikkel <mickl@itu.dk> Co-authored-by: Victor <visf@itu.dk>**

add csvfile to publish

---

src/Chirp.Razor/CheepService.cs
src/Chirp.Razor/DBFacade.cs
src/Chirp.Razor/Pages/Public.cshtml.cs
src/Chirp.Razor/Pages/UserTimeline.cshtml.cs

Add pagination to public and private timelines

---

src/Chirp.Razor/Pages/Public.cshtml.cs
src/Chirp.Razor/Pages/UserTimeline.cshtml.cs

fix page index not being 0 indexed

---

.github/workflows/main_bdsagroup4chirprazor.yml

- **Update azure publish path for Chirp.Web**
- **Update azure publish path for Chirp.Web**

update publish path azure deployment

---

src/Chirp.Web/Chirp.Web.csproj
src/Chirp.Web/Pages/Public.cshtml.cs
src/Chirp.Web/Pages/Shared/_Layout.cshtml
src/Chirp.Web/Program.cs

- **Add github login (not working)**
- **Add login and logout with github Co-authored-by: Mikkel <mikcl@itu.dk> Co-authored-by: Allan <allp@itu.dk>**
- **Add code credit to Adrian Co-authored-by: Adrian <adrianjuul123@gmail.com>**
- **Change name of env variables to make them compatible on Azure**

105 as a user i want to be able to be able to log in with my github account so as to have some sort of identity on the platform

---

src/Chirp.Core/ICheepService.cs
src/Chirp.Infrastructure/CheepService.cs
src/Chirp.Web/Pages/Public.cshtml.cs
src/Chirp.Web/Pages/UserTimeline.cshtml.cs
test/Chirp.Tests/CheepSecurityTests.cs

added testing against SQL injections and fixed service to access repository.

129 add security testing

---

.github/workflows/build_and_test.yml

I added Playwright tests from the github actions marketplace

Added Playwright testing from Microsoft

---

src/Chirp.Core/ICheepRepository.cs
src/Chirp.Core/ICheepService.cs
src/Chirp.Infrastructure/CheepRepository.cs
src/Chirp.Infrastructure/CheepService.cs
src/Chirp.Web/Pages/About.cshtml
src/Chirp.Web/Pages/About.cshtml.cs

Add liked cheeps to about me page and remove from db when user clicks forget me

Removes from db when user clicks forget me

---

src/Chirp.Core/ICheepRepository.cs
src/Chirp.Core/ICheepService.cs
src/Chirp.Infrastructure/CheepRepository.cs
src/Chirp.Infrastructure/CheepService.cs
src/Chirp.Web/Pages/About.cshtml.cs
src/Chirp.Web/Pages/UserTimeline.cshtml
src/Chirp.Web/Pages/UserTimeline.cshtml.cs

Cheep and like counter added to usertimeline

181 as a user i wanna see a like and cheep counter

---

src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs

Fixed login and logout functionality on the login and register page

Fix login and logout in register and login page

---

.github/workflows/publish.yml

- **Trying final attempt to get this to work**
- **Specified path to dll file**
- **Fixed release path**
- **My final try**

giving up with this release

---

src/Chirp.Core/ICheepRepository.cs
src/Chirp.Core/ICheepService.cs
src/Chirp.Infrastructure/CheepRepository.cs
src/Chirp.Infrastructure/CheepService.cs
src/Chirp.Web/Pages/Partials/FollowButtonModel.cs
src/Chirp.Web/Pages/Public.cshtml.cs
src/Chirp.Web/Pages/UserTimeline.cshtml
src/Chirp.Web/Pages/UserTimeline.cshtml.cs
src/Chirp.Web/Pages/_FollowButtonPartial.cshtml

Add feature Uncheep so that a user can remvoe his own cheeps

217 as a user i want to delete my own cheeps

---

src/Chirp.Web/Pages/_FollowButtonPartial.cshtml
src/Chirp.Web/wwwroot/css/style.css

Fix cheep styling and fix cheeps are shown when logged in.

188 fix invalid cheep styling

---

src/Chirp.Web/Pages/_FollowButtonPartial.cshtml

Fixed uncheep option not displayed to unautherized users.

Fix uncheep not displayed to unauthenticated users

---

src/Chirp.Core/ICheepRepository.cs
src/Chirp.Core/ICheepService.cs
src/Chirp.Infrastructure/CheepRepository.cs
src/Chirp.Infrastructure/CheepService.cs
src/Chirp.Web/Pages/Partials/FollowButtonModel.cs
src/Chirp.Web/Pages/Public.cshtml.cs
src/Chirp.Web/Pages/UserTimeline.cshtml
src/Chirp.Web/Pages/UserTimeline.cshtml.cs
src/Chirp.Web/Pages/_FollowButtonPartial.cshtml
src/Chirp.Web/wwwroot/css/style.css

Merge main to outdated branch

---

src/Chirp.Web/Pages/_FollowButtonPartial.cshtml
src/Chirp.Web/wwwroot/css/style.css

Fixed follow counter under name instead of inside the button

213 as developer i want the follow count of a user not to be displayed on followunfollow button only in the about me page
